source ~/.dotfiles/vim/Plugfile.vim
source ~/.dotfiles/vim/config/airline.vim
source ~/.dotfiles/vim/config/keybindings.vim

syntax on
colorscheme nord
highlight Normal ctermbg=None
set cursorline
set t_Co=256
highlight CursorLine term=bold cterm=bold guibg=Grey40

set hidden
set number
set relativenumber
set colorcolumn=80
set ttimeoutlen=-1
